"""empty message

Revision ID: 0008f9b2a877
Revises: 65dad796a74b
Create Date: 2020-09-07 12:15:30.691946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0008f9b2a877'
down_revision = '65dad796a74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('quality_id', sa.Integer(), nullable=True))
    op.drop_constraint('gti_table_row_ibfk_7', 'gti_table_row', type_='foreignkey')
    op.create_foreign_key(None, 'gti_table_row', 'gti_table_row_quality', ['quality_id'], ['id'])
    op.drop_column('gti_table_row', 'layer')
    op.drop_column('gti_table_row', 'quality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('gti_table_row', sa.Column('layer', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'gti_table_row', type_='foreignkey')
    op.create_foreign_key('gti_table_row_ibfk_7', 'gti_table_row', 'gti_table_row_quality', ['quality'], ['id'])
    op.drop_column('gti_table_row', 'quality_id')
    # ### end Alembic commands ###
