"""empty message

Revision ID: 02dfd80f32ad
Revises: 6c675d9c3e34
Create Date: 2020-07-06 11:01:18.613809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02dfd80f32ad'
down_revision = '6c675d9c3e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gis_curve', sa.Column('method', sa.String(length=128), nullable=False))
    op.drop_index('name', table_name='gis_curve')
    op.create_unique_constraint(None, 'gis_curve', ['method'])
    op.drop_column('gis_curve', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gis_curve', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'gis_curve', type_='unique')
    op.create_index('name', 'gis_curve', ['name'], unique=True)
    op.drop_column('gis_curve', 'method')
    # ### end Alembic commands ###
