"""empty message

Revision ID: 03450da1d21e
Revises: a6b0c091c1ee
Create Date: 2020-08-28 12:19:23.310861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03450da1d21e'
down_revision = 'a6b0c091c1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields_layers',
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields_layers')
    # ### end Alembic commands ###
