"""empty message

Revision ID: 130f92054e24
Revises: c30e73edae97
Create Date: 2020-07-07 17:05:30.627205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130f92054e24'
down_revision = 'c30e73edae97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbore', sa.Column('is_gis', sa.Boolean(), nullable=True))
    op.add_column('wellbore', sa.Column('is_gti', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellbore', 'is_gti')
    op.drop_column('wellbore', 'is_gis')
    # ### end Alembic commands ###
