"""empty message

Revision ID: 1522841db386
Revises: c5ecfad36918
Create Date: 2020-09-04 09:06:31.370389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1522841db386'
down_revision = 'c5ecfad36918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('short_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'customer', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'short_name')
    # ### end Alembic commands ###
