"""empty message

Revision ID: 1bd002aef695
Revises: b1e99090c402
Create Date: 2020-04-14 16:12:31.523504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd002aef695'
down_revision = 'b1e99090c402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_well', 'well', ['name', 'field_id', 'pad_id', 'customer_id'])
    op.drop_index('field_id', table_name='well')
    op.drop_index('name', table_name='well')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'well', ['name'], unique=True)
    op.create_index('field_id', 'well', ['field_id'], unique=True)
    op.drop_constraint('unique_well', 'well', type_='unique')
    # ### end Alembic commands ###
