"""empty message

Revision ID: 227475ece7d7
Revises: 6df926824f9b
Create Date: 2020-04-14 16:27:49.035762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227475ece7d7'
down_revision = '6df926824f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_well', 'well', type_='unique')
    op.create_unique_constraint('unique_well', 'well', ['name', 'field_id', 'pad_id', 'customer_id', 'well_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_well', 'well', type_='unique')
    op.create_unique_constraint('unique_well', 'well', ['name', 'field_id', 'pad_id', 'customer_id'])
    # ### end Alembic commands ###
