"""empty message

Revision ID: 2841ec9efd7c
Revises: 
Create Date: 2020-04-13 14:26:20.653462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2841ec9efd7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=128), nullable=True),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('pad_num', sa.String(length=128), nullable=True),
    sa.Column('well_num', sa.String(length=128), nullable=True),
    sa.Column('service_company', sa.String(length=128), nullable=True),
    sa.Column('well_section', sa.String(length=128), nullable=True),
    sa.Column('section_interval_beg', sa.String(length=128), nullable=True),
    sa.Column('section_interval_end', sa.String(length=128), nullable=True),
    sa.Column('section_diameter', sa.String(length=128), nullable=True),
    sa.Column('information', sa.String(length=128), nullable=True),
    sa.Column('title_page', sa.String(length=128), nullable=True),
    sa.Column('construct', sa.String(length=128), nullable=True),
    sa.Column('column_size', sa.String(length=128), nullable=True),
    sa.Column('well_chronology', sa.String(length=128), nullable=True),
    sa.Column('drilling_fluid_info', sa.String(length=128), nullable=True),
    sa.Column('tool_composition', sa.String(length=128), nullable=True),
    sa.Column('depth_control_data', sa.String(length=128), nullable=True),
    sa.Column('directional_survey_data', sa.String(length=128), nullable=True),
    sa.Column('main_record', sa.String(length=128), nullable=True),
    sa.Column('data_processing_and_tool_parameters', sa.String(length=128), nullable=True),
    sa.Column('second_record', sa.String(length=128), nullable=True),
    sa.Column('curve_control_pad', sa.String(length=128), nullable=True),
    sa.Column('tool_calibration', sa.String(length=128), nullable=True),
    sa.Column('las_file_design', sa.String(length=128), nullable=True),
    sa.Column('las_file_design_well_section', sa.String(length=128), nullable=True),
    sa.Column('las_file_design_parameters_section', sa.String(length=128), nullable=True),
    sa.Column('las_file_design_curve_section', sa.String(length=128), nullable=True),
    sa.Column('incorrect_RT_data', sa.String(length=128), nullable=True),
    sa.Column('data_completeness', sa.String(length=128), nullable=True),
    sa.Column('data_transfer_settings', sa.String(length=128), nullable=True),
    sa.Column('curve_names', sa.String(length=128), nullable=True),
    sa.Column('mnemonic_description', sa.String(length=128), nullable=True),
    sa.Column('points_per_meter', sa.String(length=128), nullable=True),
    sa.Column('second_table_result', sa.String(length=128), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('company_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['service_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_list__id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('tool_type', sa.String(length=128), nullable=True),
    sa.Column('tool_num', sa.String(length=128), nullable=True),
    sa.Column('calibration_date', sa.String(length=128), nullable=True),
    sa.Column('gis_date', sa.String(length=128), nullable=True),
    sa.Column('receipt_date', sa.String(length=128), nullable=True),
    sa.Column('interval_beg', sa.String(length=128), nullable=True),
    sa.Column('interval_end', sa.String(length=128), nullable=True),
    sa.Column('rt_coefficient', sa.String(length=128), nullable=True),
    sa.Column('no_data_coefficient', sa.String(length=128), nullable=True),
    sa.Column('linkage_by_depth', sa.String(length=128), nullable=True),
    sa.Column('emissions', sa.String(length=128), nullable=True),
    sa.Column('noise', sa.String(length=128), nullable=True),
    sa.Column('check_measurement', sa.String(length=128), nullable=True),
    sa.Column('cross_plot_distribution', sa.String(length=128), nullable=True),
    sa.Column('tool_indication', sa.String(length=128), nullable=True),
    sa.Column('absolute_petrophysical_values', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['check_list__id'], ['quality_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('tool_type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['service_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_path')
    op.drop_table('layer')
    op.drop_table('tool')
    op.drop_table('method')
    op.drop_table('field')
    op.drop_table('customer_email')
    op.drop_table('company_email')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('service_company')
    op.drop_table('quality_sheet')
    op.drop_table('customer')
    # ### end Alembic commands ###
