"""empty message

Revision ID: 4d1254e26b35
Revises: a19ede0e4127
Create Date: 2020-04-14 15:32:11.408424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1254e26b35'
down_revision = 'a19ede0e4127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'well', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'well', type_='unique')
    # ### end Alembic commands ###
