"""empty message

Revision ID: 52666d6bdb2f
Revises: 7691b035967f
Create Date: 2020-06-10 14:13:31.561959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52666d6bdb2f'
down_revision = '7691b035967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'well', 'well_type', ['well_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'well', type_='foreignkey')
    # ### end Alembic commands ###
