"""empty message

Revision ID: 53c7fe3c2a6f
Revises: 049a7f766fb3
Create Date: 2020-08-20 15:46:21.813845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53c7fe3c2a6f'
down_revision = '049a7f766fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_final_report',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellbore_status',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gti_table_row', sa.Column('date_T3', sa.DateTime(), nullable=True))
    op.add_column('gti_table_row', sa.Column('final_report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gti_table_row', 'gti_final_report', ['final_report_id'], ['id'])
    op.drop_column('gti_table_row', 'mud_gas_quality')
    op.drop_column('gti_table_row', 'bottom_hole_plus_igti')
    op.drop_column('gti_table_row', 'efficiency')
    op.drop_column('gti_table_row', 'bottom_hole')
    op.add_column('wellbore', sa.Column('wellbore_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wellbore', 'wellbore_status', ['wellbore_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wellbore', type_='foreignkey')
    op.drop_column('wellbore', 'wellbore_status_id')
    op.add_column('gti_table_row', sa.Column('bottom_hole', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('efficiency', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('bottom_hole_plus_igti', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('mud_gas_quality', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'gti_table_row', type_='foreignkey')
    op.drop_column('gti_table_row', 'final_report_id')
    op.drop_column('gti_table_row', 'date_T3')
    op.drop_table('wellbore_status')
    op.drop_table('gti_final_report')
    # ### end Alembic commands ###
