"""empty message

Revision ID: 5beec5053d67
Revises: e5ac060286d4
Create Date: 2020-07-23 11:15:29.170332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beec5053d67'
down_revision = 'e5ac060286d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('editable_tbl', sa.String(length=128), nullable=True),
    sa.Column('is_create', sa.Boolean(), nullable=True),
    sa.Column('is_edit', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editable_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('before_edit', sa.String(length=1024), nullable=True),
    sa.Column('after_edit', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['logger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editable_field')
    op.drop_table('logger')
    # ### end Alembic commands ###
