"""empty message

Revision ID: 65dad796a74b
Revises: d3c07a3d328d
Create Date: 2020-09-06 11:43:52.152034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dad796a74b'
down_revision = 'd3c07a3d328d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('final_report_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gti_table_row', 'final_report_path')
    # ### end Alembic commands ###
