"""empty message

Revision ID: 6c675d9c3e34
Revises: d83569666549
Create Date: 2020-07-06 10:52:18.545696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c675d9c3e34'
down_revision = 'd83569666549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_curve_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gis_curve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('latin', sa.String(length=128), nullable=False),
    sa.Column('curve_type', sa.String(length=128), nullable=False),
    sa.Column('units', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gis_curve_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gis_curve')
    op.drop_table('gis_curve_category')
    # ### end Alembic commands ###
