"""empty message

Revision ID: 6df926824f9b
Revises: dbdf514db8fc
Create Date: 2020-04-14 16:27:08.504844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df926824f9b'
down_revision = 'dbdf514db8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['name'])
    op.create_unique_constraint('unique_field', 'field', ['customer_id', 'name'])
    op.create_unique_constraint('unique_pad', 'pad', ['name', 'field_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_pad', 'pad', type_='unique')
    op.drop_constraint('unique_field', 'field', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
