"""empty message

Revision ID: 6f798e92ed42
Revises: df5ba2fcb93c
Create Date: 2020-09-08 11:54:51.535726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f798e92ed42'
down_revision = 'df5ba2fcb93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gti_table_row', 'quality')
    op.drop_column('gti_table_row', 'company')
    op.drop_column('gti_table_row', 'layer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('layer', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('company', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
