"""empty message

Revision ID: 7201cf71a707
Revises: 949336943356
Create Date: 2020-08-18 17:34:29.522777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7201cf71a707'
down_revision = '949336943356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_service_company',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gti_table_row', sa.Column('service_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gti_table_row', 'gti_service_company', ['service_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gti_table_row', type_='foreignkey')
    op.drop_column('gti_table_row', 'service_company_id')
    op.drop_table('gti_service_company')
    # ### end Alembic commands ###
