"""empty message

Revision ID: 751f8dbe7d69
Revises: 227475ece7d7
Create Date: 2020-04-14 16:30:13.599739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751f8dbe7d69'
down_revision = '227475ece7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_well', 'layer', ['name', 'field_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_well', 'layer', type_='unique')
    # ### end Alembic commands ###
