"""empty message

Revision ID: 7691b035967f
Revises: f9d2eb0810dc
Create Date: 2020-06-10 14:09:20.556986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7691b035967f'
down_revision = 'f9d2eb0810dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('well', sa.Column('well_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'well', 'well_type', ['well_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'well', type_='foreignkey')
    op.drop_column('well', 'well_type_id')
    op.drop_table('well_type')
    # ### end Alembic commands ###
