"""empty message

Revision ID: 802dbb2979e6
Revises: bdd8f3aca8ee
Create Date: 2020-08-10 12:17:40.616004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802dbb2979e6'
down_revision = 'bdd8f3aca8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('edit_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'edit_date')
    op.drop_column('user', 'create_date')
    op.drop_column('role', 'edit_date')
    op.drop_column('role', 'create_date')
    # ### end Alembic commands ###
