"""empty message

Revision ID: 8210d55f7a69
Revises: a89dc26418d3
Create Date: 2020-04-14 15:02:15.576579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8210d55f7a69'
down_revision = 'a89dc26418d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('well_ibfk_1', 'well', type_='foreignkey')
    op.drop_constraint('well_ibfk_2', 'well', type_='foreignkey')
    op.drop_column('well', 'customer_id')
    op.drop_column('well', 'field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('field_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('well', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('well_ibfk_2', 'well', 'field', ['field_id'], ['id'])
    op.create_foreign_key('well_ibfk_1', 'well', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
