"""empty message

Revision ID: 8b7c06523a22
Revises: 6f798e92ed42
Create Date: 2020-09-10 09:45:54.328018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b7c06523a22'
down_revision = '6f798e92ed42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellbores_layers_gti',
    sa.Column('wellbore_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['wellbore_id'], ['wellbore.id'], )
    )
    op.drop_table('wellbores_layers')
    op.drop_column('gti_table_row', 'layer')
    op.drop_column('gti_table_row', 'quality')
    op.drop_column('gti_table_row', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('company', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('gti_table_row', sa.Column('layer', mysql.VARCHAR(length=128), nullable=True))
    op.create_table('wellbores_layers',
    sa.Column('wellbore_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('layer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], name='wellbores_layers_ibfk_1'),
    sa.ForeignKeyConstraint(['wellbore_id'], ['wellbore.id'], name='wellbores_layers_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wellbores_layers_gti')
    # ### end Alembic commands ###
