"""empty message

Revision ID: 9a2962f526ca
Revises: 4d1254e26b35
Create Date: 2020-04-14 15:41:09.379601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2962f526ca'
down_revision = '4d1254e26b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'well', ['field_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'well', type_='unique')
    # ### end Alembic commands ###
