"""empty message

Revision ID: a31ac8e6c27c
Revises: 2de9b01dbff1
Create Date: 2020-08-10 12:09:54.784572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a31ac8e6c27c'
down_revision = '2de9b01dbff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('field', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('field', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('pad', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('pad', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('pad', 'date_add')
    op.add_column('well', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('well', 'change_date')
    op.add_column('well_type', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('well_type', 'change_date')
    op.add_column('wellbore', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('wellbore', 'change_date')
    op.add_column('wellbore_type', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('wellbore_type', 'change_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbore_type', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('wellbore_type', 'edit_date')
    op.add_column('wellbore', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('wellbore', 'edit_date')
    op.add_column('well_type', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('well_type', 'edit_date')
    op.add_column('well', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('well', 'edit_date')
    op.add_column('pad', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('pad', 'edit_date')
    op.drop_column('pad', 'create_date')
    op.drop_column('field', 'edit_date')
    op.drop_column('field', 'create_date')
    op.drop_column('customer', 'edit_date')
    op.drop_column('customer', 'create_date')
    # ### end Alembic commands ###
