"""empty message

Revision ID: a6b0c091c1ee
Revises: b6919a86cb84
Create Date: 2020-08-27 18:15:41.536809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6b0c091c1ee'
down_revision = 'b6919a86cb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_suite', table_name='suite')
    op.drop_constraint('suite_ibfk_1', 'suite', type_='foreignkey')
    op.drop_column('suite', 'field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suite', sa.Column('field_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('suite_ibfk_1', 'suite', 'field', ['field_id'], ['id'])
    op.create_index('unique_suite', 'suite', ['name', 'field_id'], unique=True)
    # ### end Alembic commands ###
