"""empty message

Revision ID: a89dc26418d3
Revises: f8ffc84de17c
Create Date: 2020-04-14 14:24:33.586337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a89dc26418d3'
down_revision = 'f8ffc84de17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pad', sa.Column('date_add', sa.DateTime(), nullable=True))
    op.drop_constraint('well_ibfk_4', 'well', type_='foreignkey')
    op.drop_column('well', 'description_part_7')
    op.drop_column('well', 'casing_shoe')
    op.drop_column('well', 'country')
    op.drop_column('well', 'description_part_8')
    op.drop_column('well', 'drilling_fluid_filtrate_resistivity')
    op.drop_column('well', 'total_depth')
    op.drop_column('well', 'well_log_beg_date')
    op.drop_column('well', 'description_part_5')
    op.drop_column('well', 'drilling_fluid_pH')
    op.drop_column('well', 'drilling_fluid_type')
    op.drop_column('well', 'mud_cake_resistivity')
    op.drop_column('well', 'altitude')
    op.drop_column('well', 'drilling_fluid_temperature')
    op.drop_column('well', 'drilling_fluid_max_temperature')
    op.drop_column('well', 'well_log_end_date')
    op.drop_column('well', 'wellbore_number')
    op.drop_column('well', 'drilling_fluid_filtrate_temperature')
    op.drop_column('well', 'well_num')
    op.drop_column('well', 'drilling_fluid_density')
    op.drop_column('well', 'drilling_fluid_mineralization')
    op.drop_column('well', '_Well__total_depth')
    op.drop_column('well', 'toolstring')
    op.drop_column('well', 'status')
    op.drop_column('well', 'description_part_4')
    op.drop_column('well', 'drilling_fluid_viscosity')
    op.drop_column('well', 'drilling_fluid_resistivity')
    op.drop_column('well', 'bit_size')
    op.drop_column('well', 'service_company_id')
    op.drop_column('well', 'description_part_3')
    op.drop_column('well', 'drilling_fluid_fluid_loss')
    op.drop_column('well', 'description_part_9')
    op.drop_column('well', 'y_coordinate')
    op.drop_column('well', 'x_coordinate')
    op.drop_column('well', 'description_part_2')
    op.drop_column('well', 'description_part_1')
    op.drop_column('well', 'serial_number')
    op.drop_column('well', 'description_part_6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('description_part_6', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('serial_number', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('description_part_1', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('description_part_2', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('x_coordinate', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('y_coordinate', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('description_part_9', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_fluid_loss', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('description_part_3', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('service_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('well', sa.Column('bit_size', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_resistivity', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_viscosity', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('description_part_4', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('status', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('toolstring', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('_Well__total_depth', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_mineralization', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_density', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('well_num', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_filtrate_temperature', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('wellbore_number', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('well_log_end_date', mysql.DATETIME(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_max_temperature', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_temperature', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('altitude', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('mud_cake_resistivity', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_type', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_pH', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('description_part_5', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('well_log_beg_date', mysql.DATETIME(), nullable=True))
    op.add_column('well', sa.Column('total_depth', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_filtrate_resistivity', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('description_part_8', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('country', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('well', sa.Column('casing_shoe', mysql.FLOAT(), nullable=True))
    op.add_column('well', sa.Column('description_part_7', mysql.VARCHAR(length=256), nullable=True))
    op.create_foreign_key('well_ibfk_4', 'well', 'service_company', ['service_company_id'], ['id'])
    op.drop_column('pad', 'date_add')
    # ### end Alembic commands ###
