"""empty message

Revision ID: b1e99090c402
Revises: 9a2962f526ca
Create Date: 2020-04-14 15:41:55.327995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e99090c402'
down_revision = '9a2962f526ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('field_id', table_name='well')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('field_id', 'well', ['field_id'], unique=True)
    # ### end Alembic commands ###
