"""empty message

Revision ID: b6919a86cb84
Revises: e06c2cc7611b
Create Date: 2020-08-27 17:02:39.039745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6919a86cb84'
down_revision = 'e06c2cc7611b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields_suites',
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['suite.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields_suites')
    # ### end Alembic commands ###
