"""empty message

Revision ID: bdd8f3aca8ee
Revises: a31ac8e6c27c
Create Date: 2020-08-10 12:14:57.658316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd8f3aca8ee'
down_revision = 'a31ac8e6c27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_email', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('company_email', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('customer_email', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('customer_email', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('file_path', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('file_path', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('gis_curve', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gis_curve', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gis_curve', 'date_add')
    op.add_column('gis_curve_category', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gis_curve_category', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('gis_curve_rename', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gis_curve_rename', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gis_curve_rename', 'date_add')
    op.add_column('gti_format', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_format', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_format', 'date_add')
    op.add_column('gti_gas_research', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_gas_research', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_gas_research', 'date_add')
    op.add_column('gti_geo_research', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_geo_research', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_geo_research', 'date_add')
    op.add_column('gti_parameter', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_parameter', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_parameter', 'date_add')
    op.add_column('gti_quality_sheet', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_quality_sheet', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_quality_sheet', 'date_add')
    op.add_column('gti_table_row', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_table_row', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_table_row', 'date_add')
    op.add_column('gti_technological_research', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('gti_technological_research', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('gti_technological_research', 'date_add')
    op.add_column('layer', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('layer', 'change_date')
    op.add_column('method', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('method', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('quality_sheet', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('quality_sheet', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('service_company', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('service_company', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.add_column('suite', sa.Column('edit_date', sa.DateTime(), nullable=True))
    op.drop_column('suite', 'change_date')
    op.add_column('tool', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('tool', sa.Column('edit_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'edit_date')
    op.drop_column('tool', 'create_date')
    op.add_column('suite', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('suite', 'edit_date')
    op.drop_column('service_company', 'edit_date')
    op.drop_column('service_company', 'create_date')
    op.drop_column('quality_sheet', 'edit_date')
    op.drop_column('quality_sheet', 'create_date')
    op.drop_column('method', 'edit_date')
    op.drop_column('method', 'create_date')
    op.add_column('layer', sa.Column('change_date', mysql.DATETIME(), nullable=True))
    op.drop_column('layer', 'edit_date')
    op.add_column('gti_technological_research', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_technological_research', 'edit_date')
    op.drop_column('gti_technological_research', 'create_date')
    op.add_column('gti_table_row', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_table_row', 'edit_date')
    op.drop_column('gti_table_row', 'create_date')
    op.add_column('gti_quality_sheet', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_quality_sheet', 'edit_date')
    op.drop_column('gti_quality_sheet', 'create_date')
    op.add_column('gti_parameter', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_parameter', 'edit_date')
    op.drop_column('gti_parameter', 'create_date')
    op.add_column('gti_geo_research', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_geo_research', 'edit_date')
    op.drop_column('gti_geo_research', 'create_date')
    op.add_column('gti_gas_research', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_gas_research', 'edit_date')
    op.drop_column('gti_gas_research', 'create_date')
    op.add_column('gti_format', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gti_format', 'edit_date')
    op.drop_column('gti_format', 'create_date')
    op.add_column('gis_curve_rename', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gis_curve_rename', 'edit_date')
    op.drop_column('gis_curve_rename', 'create_date')
    op.drop_column('gis_curve_category', 'edit_date')
    op.drop_column('gis_curve_category', 'create_date')
    op.add_column('gis_curve', sa.Column('date_add', mysql.DATETIME(), nullable=True))
    op.drop_column('gis_curve', 'edit_date')
    op.drop_column('gis_curve', 'create_date')
    op.drop_column('file_path', 'edit_date')
    op.drop_column('file_path', 'create_date')
    op.drop_column('customer_email', 'edit_date')
    op.drop_column('customer_email', 'create_date')
    op.drop_column('company_email', 'edit_date')
    op.drop_column('company_email', 'create_date')
    # ### end Alembic commands ###
