"""empty message

Revision ID: c30e73edae97
Revises: 02dfd80f32ad
Create Date: 2020-07-06 13:56:17.420120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30e73edae97'
down_revision = '02dfd80f32ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_curve_rename',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curve_id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['curve_id'], ['gis_curve.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'curve_id', name='unique_curve_rename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gis_curve_rename')
    # ### end Alembic commands ###
