"""empty message

Revision ID: c5ecfad36918
Revises: 03450da1d21e
Create Date: 2020-08-28 15:38:12.818562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5ecfad36918'
down_revision = '03450da1d21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellbores_layers',
    sa.Column('wellbore_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['wellbore_id'], ['wellbore.id'], )
    )
    op.drop_table('fields_layers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields_layers',
    sa.Column('field_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('layer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], name='fields_layers_ibfk_1'),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], name='fields_layers_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wellbores_layers')
    # ### end Alembic commands ###
