"""empty message

Revision ID: c68cd22fd9c5
Revises: 7922f9c71814
Create Date: 2020-04-18 15:18:57.834433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68cd22fd9c5'
down_revision = '7922f9c71814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbore', sa.Column('wellbore_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wellbore', 'wellbore_type', ['wellbore_type_id'], ['id'])
    op.drop_constraint('wellbore_type_ibfk_1', 'wellbore_type', type_='foreignkey')
    op.drop_column('wellbore_type', 'wellbore_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellbore_type', sa.Column('wellbore_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('wellbore_type_ibfk_1', 'wellbore_type', 'wellbore', ['wellbore_id'], ['id'])
    op.drop_constraint(None, 'wellbore', type_='foreignkey')
    op.drop_column('wellbore', 'wellbore_type_id')
    # ### end Alembic commands ###
