"""empty message

Revision ID: d0002be33e53
Revises: 5beec5053d67
Create Date: 2020-08-05 14:29:53.941130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0002be33e53'
down_revision = '5beec5053d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gti_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['gti_parameter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gti_format')
    op.drop_table('gti_parameter')
    # ### end Alembic commands ###
