"""empty message

Revision ID: d3c07a3d328d
Revises: 1522841db386
Create Date: 2020-09-06 11:27:52.390386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c07a3d328d'
down_revision = '1522841db386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['short_name'])
    op.add_column('gti_table_row', sa.Column('final_report_path', sa.String(length=256), nullable=True))
    op.add_column('gti_table_row', sa.Column('gti_quality_sheet', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gti_table_row', 'gti_quality_sheet')
    op.drop_column('gti_table_row', 'final_report_path')
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
