"""empty message

Revision ID: d83569666549
Revises: 6f33667e695c
Create Date: 2020-06-23 16:08:23.450125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd83569666549'
down_revision = '6f33667e695c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_sheet', sa.Column('service_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quality_sheet', 'service_company', ['service_company_id'], ['id'])
    op.drop_column('quality_sheet', 'service_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_sheet', sa.Column('service_company', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'quality_sheet', type_='foreignkey')
    op.drop_column('quality_sheet', 'service_company_id')
    # ### end Alembic commands ###
