"""empty message

Revision ID: d97db56727cc
Revises: 5d86f54452da
Create Date: 2020-04-15 11:28:34.023733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97db56727cc'
down_revision = '5d86f54452da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('change_date', sa.DateTime(), nullable=True))
    op.add_column('layer', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('well', sa.Column('change_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'change_date')
    op.drop_column('layer', 'create_date')
    op.drop_column('layer', 'change_date')
    # ### end Alembic commands ###
