"""empty message

Revision ID: da0d285bf07a
Revises: 3080837eec76
Create Date: 2020-07-17 12:37:45.730982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0d285bf07a'
down_revision = '3080837eec76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_quality_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('gti_table_row_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gti_table_row_id'], ['gti_table_row.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gti_quality_sheet')
    # ### end Alembic commands ###
