"""empty message

Revision ID: dbdf514db8fc
Revises: 1bd002aef695
Create Date: 2020-04-14 16:19:15.546131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdf514db8fc'
down_revision = '1bd002aef695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('pad_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('well_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['pad_id'], ['pad.id'], ),
    sa.ForeignKeyConstraint(['well_type_id'], ['well_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'field_id', 'pad_id', 'customer_id', name='unique_well')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('well')
    # ### end Alembic commands ###
