"""empty message

Revision ID: dc027d100f37
Revises: c68cd22fd9c5
Create Date: 2020-04-18 15:20:45.489635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc027d100f37'
down_revision = 'c68cd22fd9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_wellbore_type', 'wellbore', type_='unique')
    op.create_unique_constraint('unique_wellbore_type', 'wellbore', ['name', 'wellbore_type_id', 'well_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_wellbore_type', 'wellbore', type_='unique')
    op.create_unique_constraint('unique_wellbore_type', 'wellbore', ['name', 'well_id'])
    # ### end Alembic commands ###
