"""empty message

Revision ID: dc2073687cde
Revises: 4e595ad232ae
Create Date: 2020-07-13 14:11:35.219019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2073687cde'
down_revision = '4e595ad232ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_table_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('wellbore_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('layer', sa.String(length=128), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('efficiency', sa.String(length=128), nullable=False),
    sa.Column('mud_gas_quality', sa.String(length=128), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('bottom_hole_plus_igti', sa.String(length=128), nullable=False),
    sa.Column('bottom_hole', sa.String(length=128), nullable=False),
    sa.Column('degasser', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['wellbore_id'], ['wellbore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_gti',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_row_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_row_id'], ['gti_table_row.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_gti')
    op.drop_table('gti_table_row')
    # ### end Alembic commands ###
