"""empty message

Revision ID: df5ba2fcb93c
Revises: 0008f9b2a877
Create Date: 2020-09-08 11:49:57.356951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df5ba2fcb93c'
down_revision = '0008f9b2a877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gti_table_row', 'layer')
    op.drop_column('gti_table_row', 'company')
    op.drop_column('gti_table_row', 'quality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_table_row', sa.Column('quality', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('gti_table_row', sa.Column('company', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_table_row', sa.Column('layer', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
