"""empty message

Revision ID: e14b7996f6e1
Revises: 6d8e613e37dd
Create Date: 2020-05-10 16:39:49.618221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e14b7996f6e1'
down_revision = '6d8e613e37dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
