"""empty message

Revision ID: e5ac060286d4
Revises: da0d285bf07a
Create Date: 2020-07-22 19:04:20.418654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ac060286d4'
down_revision = 'da0d285bf07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gti_gas_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('interval_beg', sa.Integer(), nullable=True),
    sa.Column('interval_end', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('parameter', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('falsification', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gti_geo_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('interval_beg', sa.Integer(), nullable=True),
    sa.Column('interval_end', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('parameter', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('falsification', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gti_technological_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('interval_beg', sa.Integer(), nullable=True),
    sa.Column('interval_end', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('parameter', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('falsification', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gti_technological_research')
    op.drop_table('gti_geo_research')
    op.drop_table('gti_gas_research')
    # ### end Alembic commands ###
