"""empty message

Revision ID: ef6d1b639a64
Revises: d0002be33e53
Create Date: 2020-08-05 15:06:59.430258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d1b639a64'
down_revision = 'd0002be33e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_format', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('gti_parameter', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gti_parameter', 'name')
    op.drop_column('gti_format', 'name')
    # ### end Alembic commands ###
