"""empty message

Revision ID: f8ffc84de17c
Revises: b1466c8dea35
Create Date: 2020-04-14 10:57:33.523571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8ffc84de17c'
down_revision = 'b1466c8dea35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.add_column('well', sa.Column('drilling_fluid_density', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_filtrate_resistivity', sa.String(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_filtrate_temperature', sa.String(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_fluid_loss', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_max_temperature', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_mineralization', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_pH', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_resistivity', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_temperature', sa.String(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_type', sa.String(length=256), nullable=True))
    op.add_column('well', sa.Column('drilling_fluid_viscosity', sa.Float(), nullable=True))
    op.add_column('well', sa.Column('mud_cake_resistivity', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'mud_cake_resistivity')
    op.drop_column('well', 'drilling_fluid_viscosity')
    op.drop_column('well', 'drilling_fluid_type')
    op.drop_column('well', 'drilling_fluid_temperature')
    op.drop_column('well', 'drilling_fluid_resistivity')
    op.drop_column('well', 'drilling_fluid_pH')
    op.drop_column('well', 'drilling_fluid_mineralization')
    op.drop_column('well', 'drilling_fluid_max_temperature')
    op.drop_column('well', 'drilling_fluid_fluid_loss')
    op.drop_column('well', 'drilling_fluid_filtrate_temperature')
    op.drop_column('well', 'drilling_fluid_filtrate_resistivity')
    op.drop_column('well', 'drilling_fluid_density')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
