"""empty message

Revision ID: fc2071d3da54
Revises: 802dbb2979e6
Create Date: 2020-08-14 15:55:25.578993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc2071d3da54'
down_revision = '802dbb2979e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_gas_research', sa.Column('counterfeit', sa.String(length=1024), nullable=True))
    op.add_column('gti_gas_research', sa.Column('quality_sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gti_gas_research', 'gti_quality_sheet', ['quality_sheet_id'], ['id'])
    op.drop_column('gti_gas_research', 'format')
    op.drop_column('gti_gas_research', 'parameter')
    op.drop_column('gti_gas_research', 'falsification')
    op.add_column('gti_geo_research', sa.Column('counterfeit', sa.String(length=1024), nullable=True))
    op.add_column('gti_geo_research', sa.Column('quality_sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gti_geo_research', 'gti_quality_sheet', ['quality_sheet_id'], ['id'])
    op.drop_column('gti_geo_research', 'format')
    op.drop_column('gti_geo_research', 'parameter')
    op.drop_column('gti_geo_research', 'falsification')
    op.add_column('gti_parameter', sa.Column('technological_research_row_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gti_parameter', 'gti_technological_research', ['technological_research_row_id'], ['id'])
    op.add_column('gti_technological_research', sa.Column('counterfeit', sa.String(length=1024), nullable=True))
    op.add_column('gti_technological_research', sa.Column('quality_sheet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gti_technological_research', 'gti_quality_sheet', ['quality_sheet_id'], ['id'])
    op.drop_column('gti_technological_research', 'format')
    op.drop_column('gti_technological_research', 'parameter')
    op.drop_column('gti_technological_research', 'falsification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gti_technological_research', sa.Column('falsification', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_technological_research', sa.Column('parameter', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_technological_research', sa.Column('format', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'gti_technological_research', type_='foreignkey')
    op.drop_column('gti_technological_research', 'quality_sheet_id')
    op.drop_column('gti_technological_research', 'counterfeit')
    op.drop_constraint(None, 'gti_parameter', type_='foreignkey')
    op.drop_column('gti_parameter', 'technological_research_row_id')
    op.add_column('gti_geo_research', sa.Column('falsification', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_geo_research', sa.Column('parameter', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_geo_research', sa.Column('format', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'gti_geo_research', type_='foreignkey')
    op.drop_column('gti_geo_research', 'quality_sheet_id')
    op.drop_column('gti_geo_research', 'counterfeit')
    op.add_column('gti_gas_research', sa.Column('falsification', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_gas_research', sa.Column('parameter', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('gti_gas_research', sa.Column('format', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'gti_gas_research', type_='foreignkey')
    op.drop_column('gti_gas_research', 'quality_sheet_id')
    op.drop_column('gti_gas_research', 'counterfeit')
    # ### end Alembic commands ###
